### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by this-is-dimpi** [James4Ever0/agi_computer_control#3]
Hello @James4Ever0 , Could you please help on below issue? I am not able to conclude whether we expect results in bytes or str.

2023-08-18 04:24:53,542Z INFO  rdp_client_cli.py:227 (TB) Initiate RDP connection: (IP:10.48.183.172, Username:devuser,      Password:nutanix/4u, Domain:XI88.local)
Unhandled Error
Traceback (most recent call last):
File "/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/python/log.py", line 96, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/python/log.py", line 80, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
--- <exception caught here> ---
  File "/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/internet/posixbase.py", line 487, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/internet/tcp.py", line 248, in doRead
    return self._dataReceived(data)
  File "/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/internet/tcp.py", line 253, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/protocols/tls.py", line 329, in dataReceived
    self._flushReceiveBIO()
  File "/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/protocols/policies.py", line 110, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/rdpy3/protocol/rdp/nla/cssp.py", line 259, in recvChallenge
    message, self._interface = self._authenticationProtocol.getAuthenticateMessage(getNegoTokens(request)[0])
  File "/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/rdpy3/protocol/rdp/nla/ntlm.py", line 552, in getAuthenticateMessage
    NtChallengeResponse, LmChallengeResponse, SessionBaseKey = ComputeResponsev2(self._ResponseKeyNT, self._ResponseKeyLM, ServerChallenge, ClientChallenge, Timestamp, ServerName)
  File "/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/rdpy3/protocol/rdp/nla/ntlm.py", line 452, in ComputeResponsev2
    temp = Responserversion + HiResponserversion + Z(6) + Time + ClientChallenge + Z(4) + ServerName
builtins.TypeError: can only concatenate str (not "bytes") to str

[*] INFO: *******************************************
[*] INFO: *          NLA Security selected          *
[*] INFO: *******************************************
Dimpi Responserversion: <class 'str'>, HiResponserversion: <class 'str'>, Z(6): <class 'str'>, Time: <class 'bytes'>, ClientChallenge : <class 'bytes'>, Z(4): <class 'str'>, ServerName: <class 'bytes'>
2023-08-18 04:24:53,572Z INFO  rdp_client_cli.py:167 (TB) Lost connection : [Failure instance: Traceback: <class 'TypeError'>: can only concatenate str (not "bytes") to str
/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/python/log.py:80:callWithContext
/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/python/context.py:117:callWithContext
/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/python/context.py:82:callWithContext
/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/internet/posixbase.py:500:_doReadOrWrite
--- <exception caught here> ---
/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/internet/posixbase.py:487:_doReadOrWrite
/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/internet/tcp.py:248:doRead
/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/internet/tcp.py:253:_dataReceived
/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/protocols/tls.py:329:dataReceived
/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/protocols/tls.py:295:_flushReceiveBIO
/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/twisted/protocols/policies.py:110:dataReceived
/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/rdpy3/protocol/rdp/nla/cssp.py:259:recvChallenge
/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/rdpy3/protocol/rdp/nla/ntlm.py:552:getAuthenticateMessage
/home/dimple.goyal/ADUI/nutest-py3-tests/my_nutest_virtual_env/lib/python3.9/site-packages/rdpy3/protocol/rdp/nla/ntlm.py:452:ComputeResponsev2

**Comment by James4Ever0** [comment]
This is not relevant to my project. Do not post this issue here.
Do not contact me for this anymore. I am not responsible for this.
